### ISSUE TITLE
Violation of Codewars terms, risk of account being banned

### ISSUE THREAD

**Issue by jhoffner** [Automedon/CodeWars-7-kyu-Soluitions#1]
Please this repository private. This is in violation of Codewar's terms. By exposing your solutions you are making it easy for others to cheat with your solutions, which will result in your account being banned. 

All public solutions need to be made private on Github, including any other repositories you may have which provide solutions to Codewars' content.

**Comment by Automedon** [comment]
According to Codewar's terms.

**To promote collaboration and create a living resource, all kata solutions are actively opensourced under the FreeBSD 2-Clause License.**

P.S. No one could stop a human being if he want to cheat.
P.S.2 [Readme](https://github.com/Automedon/CodeWars-7-kyu-Soluitions/blob/master/README.md)
